version: '3.8'

services:
  tgbot-translator:
    build: .
    container_name: tgbot-translator
    environment:
      - BOT_TOKEN=
      - AI_API_KEY=
      - AI_API_ENDPOINT=
      - AI_MODEL=
    volumes:
      - ./userConfig.json:/app/userConfig.json:ro
    restart: unless-stopped
